appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: tbSHmqElLUjdOjG0RmoXs2aJXwdUW206g/k1hkK+CpXqIUQatdC2yp52SnZBOKop/VWQX0TKpSRVFmD17TRSV9/5AdPVkxW2S5c3k3jeYkoPkTX7xQfleBE6tGGXJnpTyZl248Wz4//G9bf8GjRdx00IlOhszSfHE2ALj5kzOyq+IJDx7QvhNhwXHvJCm/RVFhpYLpiqQjNJPKjcz3JhCOENUjHR+l9BRZ7GOfaFRhlGmItC6pg1xsRksQFX/6bOt5yvEpqKSrfGtCwbkqzAC0lcmAJuXCcYmJQZe53C7vv4MXiiYTW5Sw/3jGP1csVmijQeGO+T5BxETofKIJ37fCpCCVNGbcaL2+S2t9bIV+EoYbXbQwV4rslgtnAHZNegXhMoTlTNchtEdi/DEdfMreLwe42lyYuuklL/EIuRALaOlB7jcKwc9OXWXsoZpaPnuK9LyXxNYik4s0hQEFbE78N2R7l9nfPEZcWODvkSYz8OUhxH8ydggzWg/u7ZpA57UIXKjPRVdSlqcTiGdOfWRRLUp/9VutjqaLV1cq+Ix4zWGQOAsAkyUctszM50rJmqCEgrf6iFjUt9AAT8g7BpM7N0ihbuwtGD3asX+mEHBYo9Y/E4r2Vn3FuAl+ePihNtXfyhb1R8IDbp3+ML8t//cXgyFktzVcUfNOGtS4Y7yDI=}
